[package]
name = "postinteraction"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[workspace]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3"
serde = "1.0.130"
serde_json = "1.0.68"
