[package]
name = "postinteraction"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[workspace]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
yaml-rust = "0.4.5"
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"



[dependencies.ecdsa]
version = "0.12.4"

[dependencies.ed25519-dalek]
version = "1"