Write-Host "Version ~> 1.0V"
Write-Host "Is it currently compatible with Docker? No"

Write-Host "Ok [1/2]"
Invoke-Expression "go build"
Write-Host "Ok [2/2]"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Everything is ready. Just run "post-interaction.exe" and it will run automatically"
Write-Host "Thank you for downloading and using this package to extend your base."
Write-Host ""
Write-Host "If you want to help contribute, go to this project's Github."
Write-Host "https://github.com/RabbitHouseCorp/post-interaction"